networks:
  lab:
    name: lab
    external: true

services:
  lb0:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    image: k8s-haproxy:local  
    container_name: k8s-lb0
    hostname: lb0
    networks:
      - lab
    tty: true
    restart: on-failure:1
    ports:
      - "6443"

  master0:
    &node-template
    build:
      context: ./k8s-ready
      dockerfile: Dockerfile
    image: k8s-ready:local
    container_name: k8s-master0
    hostname: master0
    networks:
      - lab
    privileged: true
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tty: true
    restart: always
    pid: "host"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
      - ./data/kubelet:/var/lib/kubelet
      - ./data/kubernetes:/etc/kubernetes
    environment:
      - container=docker
      - DEBIAN_FRONTEND=noninteractive
      - SYSTEMD_IGNORE_CHROOT=1
    cap_add:
      - ALL
    stop_signal: SIGRTMIN+3
    command: /bin/bash -c "sleep infinity"

  master1:
    <<: *node-template
    container_name: k8s-master1
    hostname: master1

  worker0:
    <<: *node-template
    container_name: k8s-worker0
    hostname: worker0

  worker1:
    <<: *node-template
    container_name: k8s-worker1
    hostname: worker1

  worker2:
    <<: *node-template
    container_name: k8s-worker2
    hostname: worker2